config/routes.rb
Fresk::Application.routes.draw do
  devise_for :users
  get '/start', to: 'users/base#index', as: :user_root

  resources :task_lists, module: 'users' do
    resources :tasks, only: [:new, :create]
  end

  resources :watched_task_lists, module: 'users', only: [:index, :create, :destroy]

  get 'not_found', to: 'home#not_found'

  root to: 'home#index'

  get '*anything', to: 'home#not_found'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :omniauthable
  #
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable


  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :name, :username, :avatar, :remote_avatar_url, :avatar_cache, :login

  attr_readonly :task_lists_count

  # Virtual attribute allowing authentication via username or email
  #
  attr_accessor :login

  mount_uploader :avatar, AvatarUploader

  validates :name,
            presence: true

  validates :email,
            presence: true,
            uniqueness: true

  validates :username,
            presence: true,
            uniqueness: true

  validates :avatar,
            presence: true


  has_many :task_lists,
           order: 'updated_at',
           dependent: :destroy

  has_many :watchings,
           dependent: :destroy

  has_many :watched_task_lists,
           through: :watchings,
           source: :task_list,
           conditions: { public: true }

  # Overwrite Devise's database authentication method in order to provide login
  # by username or email.
  #
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where('username = :login OR lower(email) = :login', login: login).first
    else
      where(conditions).first
    end
  end
  
  # Returns a boolean indicating whether or not the user is watching the passed
  # task list
  #
  def watches?(task_list)
    watched_task_lists.include?(task_list)
  end

  # Returns a boolean indicating whether or not the user owns the passed
  # task list
  #
  def owns?(task_list)
    task_list.owner == self
  end
end

app/controllers/users/base_controller.rb
module Users

  class BaseController < ApplicationController
    before_filter :authenticate_user!

    def index
    end

    private

    def get_task_list
      task_list = TaskList.find(params[:task_list_id] || params[:id])

      if task_list.can_be_visited_by?(current_user)
        task_list
      else
        render_404
      end
    end
  end

end

app/controllers/users/task_lists_controller.rb
module Users

  class TaskListsController < BaseController
    before_filter :verify_ownership, except: [:index, :show, :new, :create]

    def index
      @task_lists = current_user.task_lists
      respond_with(@task_lists)
    end

    def new
      @task_list = current_user.task_lists.build
      respond_with(@task_lists)
    end

    def edit
      @task_list = get_task_list
    end

    def show
      @task_list = get_task_list
    end

    def create
      @task_list = current_user.task_lists.build(params[:task_list])
      @task_list.save

      respond_with(@task_list)
    end

    def update
      @task_list = get_task_list
      @task_list.update_attributes(params[:task_list])

      respond_with(@task_list)
    end

    def destroy
      @task_list = get_task_list
      @task_list.destroy

      respond_with(@task_list)
    end


    private

    def verify_ownership
      render_404 unless get_task_list.owner == current_user
    end

  end
end

app/controllers/users/tasks_controller.rb
module Users

  class TasksController < BaseController

    def index
      @task_list = get_task_list
      redirect_to @task_list
    end

    def new
      @task_list = get_task_list
      @task      = @task_list.tasks.build
    end

    def create
      @task_list = get_task_list
      @task      = @task_list.tasks.create(params[:task])
      @task.save

      respond_with(@task) do |format|
        format.html { redirect_to @task_list }
      end
    end

  end

end

app/controllers/users/watched_task_lists_controller.rb
module Users

  class WatchedTaskListsController < BaseController

    def index
      @watched_task_lists = current_user.watched_task_lists
      respond_with(@watched_task_lists)
    end

    def create
      @task_list = TaskList.public_lists.find(params[:id])
      render_404 unless @task_list.can_be_watched_by?(current_user)

      current_user.watched_task_lists << @task_list
      flash[:notice] = "You are now watching #{@task_list.name}"

      redirect_to watched_task_lists_path
    end

    def destroy
      @task_list = TaskList.public_lists.find(params[:id])
      current_user.watched_task_lists.delete(@task_list)
      flash[:notice] = "You are no longer watching #{@task_list.name}"

      redirect_to watched_task_lists_path
    end

  end

end

app/views/users/base/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container" style="width: auto;">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <span class="brand"><%= current_user.username %></span>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Your task lists', task_lists_path %></li>
          <li><%= link_to 'Watched task lists', watched_task_lists_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </div><!-- /.nav-collapse -->
    </div>
  </div><!-- /navbar-inner -->
</div><!-- /navbar -->

<br /><br />

app/views/users/base/_upcoming_task.html.erb
<div class="row">

  You have to <span class="task"><%= task.description %></span>

  in <%= distance_of_time_in_words_to_now(task.deadline) %>

  (<%= link_to "More from #{task.task_list.name}", task_list_path(task.task_list) %>)
</div>

<br />

app/views/users/base/_upcoming_watched_task.html.erb
<div class="row">
  <div class="span2">
    <%= image_tag task.task_list.owner.avatar_url(:thumb) %>
  </div>

  <div class="span6">
    <b><%= task.task_list.owner.username %></b> 
    has to <span class="task"><%= task.description %></span>

    in <%= distance_of_time_in_words_to_now(task.deadline) %>

    (<%= link_to "More from #{task.task_list.name}", task_list_path(task.task_list) %>)
  </div>

</div>

<br />

app/views/users/base/index.html.erb
<div class="row">
  <div class="span1">
    <%= image_tag current_user.avatar_url(:thumb) %>
  </div>

  <div class="span3">
    <h3>Hello, <%= current_user.username %>!</h3>
  </div>

</div>

<hr />

<% present current_user do |p| %>
  <h2>Upcoming Tasks</h2>
  <br /><br />
  <%= p.upcoming_tasks %>

  <hr />

  <h2>Upcoming Watched Tasks</h2>
  <br /><br />
  <%= p.upcoming_watched_tasks %>
<% end %>