config/routes.rb
Fresk::Application.routes.draw do
  devise_for :users
  get '/start', to: 'users/base#index', as: :user_root

  resources :task_lists, module: 'users' do
    resources :tasks, only: [:new, :create]
  end

  resources :watched_task_lists, module: 'users', only: [:index, :create, :destroy]

  get 'not_found', to: 'home#not_found'

  root to: 'home#index'

  get '*anything', to: 'home#not_found'

end

app/models/task_list.rb
require 'accessible'

class TaskList < ActiveRecord::Base
  # We can allow the `public' attribute to be mass-assigned since
  # task list creation is protected by an authentication filter.
  #
  attr_accessible :name, :public, :tasks_attributes

  belongs_to :owner,
             class_name: 'User',
             foreign_key: :user_id,
             counter_cache: true

  has_many :tasks,
           order: 'deadline',
           dependent: :destroy

  has_many :watchings,
           dependent: :destroy

  has_many :watchers,
           through: :watchings,
           source: :user

  accepts_nested_attributes_for :tasks, allow_destroy: true

  attr_readonly :tasks_count

  validates :name,
            presence: true,
            uniqueness: { scope: :user_id }

  # List task lists in the order they were last updated
  #
  default_scope order("#{table_name}.updated_at DESC")

  scope :public_lists, where(public: true)

  # Indicates whether or not this is a private task list
  #
  def private?
    !self.public
  end

  # SEO-friendly URLs
  #
  def to_param
    "#{id}-#{name.parameterize}"
  end

  # A task list is responsible for knowning if it can be visited or watched
  # by a particular user.
  #
  def can_be_visited_by?(user)
    visit_rules.apply(user, self)
  end

  def can_be_watched_by?(user)
    watch_rules.apply(user, self)
  end

  private

  def visit_rules
    @visit_rules ||= initialize_visit_rules
  end

  def watch_rules
    @watch_rules ||= initialize_watch_rules
  end

  def initialize_visit_rules
    rules = Accessible::Rules.new
    rules.add do |user, task_list|
      task_list.owner == user || task_list.public?
    end
  end

  def initialize_watch_rules
    rules = Accessible::Rules.new
    rules.add do |user, task_list|
      task_list.owner != user && task_list.public?
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :omniauthable
  #
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable


  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :name, :username, :avatar, :remote_avatar_url, :avatar_cache, :login

  attr_readonly :task_lists_count

  # Virtual attribute allowing authentication via username or email
  #
  attr_accessor :login

  mount_uploader :avatar, AvatarUploader

  validates :name,
            presence: true

  validates :email,
            presence: true,
            uniqueness: true

  validates :username,
            presence: true,
            uniqueness: true

  validates :avatar,
            presence: true


  has_many :task_lists,
           order: 'updated_at',
           dependent: :destroy

  has_many :watchings,
           dependent: :destroy

  has_many :watched_task_lists,
           through: :watchings,
           source: :task_list,
           conditions: { public: true }

  # Overwrite Devise's database authentication method in order to provide login
  # by username or email.
  #
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where('username = :login OR lower(email) = :login', login: login).first
    else
      where(conditions).first
    end
  end
  
  # Returns a boolean indicating whether or not the user is watching the passed
  # task list
  #
  def watches?(task_list)
    watched_task_lists.include?(task_list)
  end

  # Returns a boolean indicating whether or not the user owns the passed
  # task list
  #
  def owns?(task_list)
    task_list.owner == self
  end
end

app/controllers/users/base_controller.rb
module Users

  class BaseController < ApplicationController
    before_filter :authenticate_user!

    def index
    end

    private

    def get_task_list
      task_list = TaskList.find(params[:task_list_id] || params[:id])

      if task_list.can_be_visited_by?(current_user)
        task_list
      else
        render_404
      end
    end
  end

end

app/controllers/users/task_lists_controller.rb
module Users

  class TaskListsController < BaseController
    before_filter :verify_ownership, except: [:index, :show, :new, :create]

    def index
      @task_lists = current_user.task_lists
      respond_with(@task_lists)
    end

    def new
      @task_list = current_user.task_lists.build
      respond_with(@task_lists)
    end

    def edit
      @task_list = get_task_list
    end

    def show
      @task_list = get_task_list
    end

    def create
      @task_list = current_user.task_lists.build(params[:task_list])
      @task_list.save

      respond_with(@task_list)
    end

    def update
      @task_list = get_task_list
      @task_list.update_attributes(params[:task_list])

      respond_with(@task_list)
    end

    def destroy
      @task_list = get_task_list
      @task_list.destroy

      respond_with(@task_list)
    end


    private

    def verify_ownership
      render_404 unless get_task_list.owner == current_user
    end

  end
end

app/controllers/users/tasks_controller.rb
module Users

  class TasksController < BaseController

    def index
      @task_list = get_task_list
      redirect_to @task_list
    end

    def new
      @task_list = get_task_list
      @task      = @task_list.tasks.build
    end

    def create
      @task_list = get_task_list
      @task      = @task_list.tasks.create(params[:task])
      @task.save

      respond_with(@task) do |format|
        format.html { redirect_to @task_list }
      end
    end

  end

end

app/controllers/users/watched_task_lists_controller.rb
module Users

  class WatchedTaskListsController < BaseController

    def index
      @watched_task_lists = current_user.watched_task_lists
      respond_with(@watched_task_lists)
    end

    def create
      @task_list = TaskList.public_lists.find(params[:id])
      render_404 unless @task_list.can_be_watched_by?(current_user)

      current_user.watched_task_lists << @task_list
      flash[:notice] = "You are now watching #{@task_list.name}"

      redirect_to watched_task_lists_path
    end

    def destroy
      @task_list = TaskList.public_lists.find(params[:id])
      current_user.watched_task_lists.delete(@task_list)
      flash[:notice] = "You are no longer watching #{@task_list.name}"

      redirect_to watched_task_lists_path
    end

  end

end

app/helpers/task_lists_helper.rb
module TaskListsHelper

  # Renders a lock icon if the task list is private, or an unlock icon if it
  # is public.
  #
  def task_list_icon(task_list)
    html_class = task_list.public? ? 'icon-unlock' : 'icon-lock'
    icon(html_class)
  end

  # A trash can
  #
  def remove_task_list_icon
    icon('icon-trash')
  end

  # An open eye.
  #
  def task_list_watch_icon
    icon('icon-eye-open')
  end

  # A closed eye
  #
  def task_list_unwatch_icon
    icon('icon-eye-close')
  end

  # Produces a link to start watching/unwatching the task list passed as argument
  #
  def link_to_watch(task_list, user=current_user)
    return unless task_list.can_be_watched_by?(user)

    if user.watches?(task_list)
      task_list_unwatch_icon + link_to('Unwatch', watched_task_list_path(task_list),
                                       method: :delete)
    else
      task_list_watch_icon + link_to('Watch', watched_task_lists_path(id: task_list.id), 
                                     method: :post)
    end
  end
end

app/views/users/task_lists/_task_fields.html.erb
<fieldset>
  <%= prepended_text_field :description, builder do %>
    <%= content_tag :span, 'What do you have to do?', class: 'add-on' %>
    <%= builder.input_field :description, placeholder: 'Task description' %>
  <% end %>

  <%= builder.input :deadline %>

  <%# Hidden field whose value is changed in JavaScript if the user clicks the
    "Remove Task" link. Adapted from Railscasts #196 %>
  <%= builder.input :_destroy, as: :hidden %>
  <%= link_to 'Remove Task', '#', class: 'remove_fields' %>

  <br /><hr />
</fieldset>

app/views/users/task_lists/_task_list.html.erb
<%= render partial: 'task_list_summary', object: @task_list, as: :task_list %>

<%= render @task_list.tasks %>

app/views/users/task_lists/_task_list_fields.html.erb
<fieldset>
  <legend><%= legend %></legend>

  <%= prepended_text_field :name, builder do %>
    <%= content_tag :span, 'Give it a name!', class: 'add-on' %>
    <%= builder.input_field :name, placeholder: 'Must be unique!' %>
  <% end %>

  <%= builder.input :public, label: 'Public?' %>

  <h2>Tasks</h2>

  <%= builder.simple_fields_for :tasks do |tasks_form| %>
    <%= render 'task_fields', builder: tasks_form %>
  <% end %>

  <br /><br />
  <%= link_to_add_fields 'New task', form_builder: builder, association: :tasks %>

  <div class="form-actions">
    <%= builder.button :submit, class: 'btn-primary' %>
  </div>
</fieldset>

app/views/users/task_lists/_task_list_summary.html.erb
<div class="row well">
  <div class="span2">
    <b><%= link_to task_list.name, task_list_path(task_list) %></b>
  </div>

  <div class="span1">
    <%= task_list_icon(task_list) %>
  </div>

  <div class="span2">
    (<%= pluralize(task_list.tasks.size, 'task') %>)
  </div>

  <div class="span2">
    <%= link_to_watch task_list %>
  </div>

  <div class="span1">
    <% if current_user.owns?(task_list) %>
      <%= link_to remove_task_list_icon, task_list, method: :delete, title: 'Remove task list' %>
    <% end %>
  </div>
</div>

app/views/users/task_lists/edit.html.erb
<%= simple_form_for @task_list, html: { class: 'form-horizontal' } do |f| %>
  <%= render 'task_list_fields', builder: f, legend: %Q(Edit "#{@task_list.name}") %>
<% end %>

app/views/users/task_lists/index.html.erb
<h1>Your Task Lists</h1>

<br /><br />

<%= render(partial: 'task_list_summary', collection: @task_lists, as: :task_list) || 'There are no task lists.' %>

<br /><br />

<p>
  <%= link_to 'Create a new task list', new_task_list_path %>
</p>

app/views/users/task_lists/new.html.erb
<%= simple_form_for @task_list, html: { class: 'form-horizontal' } do |f| %>
  <%= render 'task_list_fields', builder: f, legend: 'New task list' %>
<% end %>

app/views/users/task_lists/show.html.erb
<h1>Details</h1>

<%= render @task_list %>

<p>
  <% if @task_list.owner == current_user %>
    <%= link_to'Edit this task list', edit_task_list_path(@task_list) %>
  <% end %>
</p>